---
- hosts: tag_Name_Server
  sudo: True
  gather_facts: no
  vars:
    - resourcesDir: resources
    - user: webapp
    - group: webapp
    - document_root: '/var/www/app/'

  tasks:
    - name: clear app dir
      file: path={{document_root}}/* state=absent

    - name: deploying
      unarchive: src=app.zip dest={{document_root}}/

    - name: change owner of app files
      file: path={{document_root}} owner={{user}} group={{group}} recurse=yes
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
